# -*- coding: utf-8 -*-
"""programming assignment11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ktZC3TcxWqLQ4KApe-Mf7Lw77gfCrt6W

1. Write a Python program to find words which are greater than given length k?
"""

a=["ineuron","class","data science","asif"]
length=5
try:
  for i in  a:
     if len(i)>length:
       print(i)
except Exception as e:
  print("there is an error",e)

"""2. Write a Python program for removing i-th character from a string?"""

a="ineuronclass"
if type(a)==str:
    new=a[:3]
    new1=a[4:]
    k=new+new1
    print(k)
else: 
  print("enter the correct value")

"""3. Write a Python program to split and join a string?"""

name="siddalinga patil"
if type(name)==str:
    h= "$".join(name)
    k=name.split(" ")
    print(h)
    print(k)
else:
  print("enterd wrong value")

"""4. Write a Python to check if a given string is binary string or not?"""

string=set("101010165310")
b={"0","1"}
if b==string or string=={"0"} or string=={"1"}:
  print("it is a binary")
else:
  print("it is not binary")

"""6. Write a Python to find all duplicate characters in string?"""

string = input()
dups=[]
for i in string:
  if string.count(i)>1 and i not in dups:
      dups.append(i)
print(f'The duplicate characters are {dups}')

"""7. Write a Python Program to check if a string contains any special character?"""

a="ineur#on"
b=["$","@","#","%","*"]
for i in a:
  for j in  b:
    if i==j:
       print("it contains")

